<h4 style="border-bottom: 1px solid #ccc" >Basic Feed Settings</h4>
        <p><label>Content Type: </label>
    	<select id="<?php echo $this->get_field_id( 'post_type' ); ?>" name="<?php echo $this->get_field_name( 'post_type' ); ?>">
        	<option value="any" <?php selected( $val['post_type'], 'any'); ?>>Any</option>
            <?php foreach( $post_types as $post_type ):?>
            <option value="<?php echo $post_type['id'];?>" <?php selected( $val['post_type'], $post_type['id']); ?> ><?php echo $post_type['title'];?></option>
            <?php endforeach;?>
        </select></p>
        <p><label>Feed By: </label>
    	<select id="<?php echo $this->get_field_id( 'taxonomy' ); ?>" name="<?php echo $this->get_field_name( 'taxonomy' ); ?>">
        	<option value="all" <?php selected( $val['taxonomy'], 'all'); ?>>All</option>
            <option value="category" <?php selected( $val['taxonomy'], 'category'); ?>>Categories</option>
            <option value="tag" <?php selected( $val['taxonomy'], 'tag'); ?>>Tags</option>
        </select></p>
        <p><label>Names: </label>
    	<input type="text" id="<?php echo $this->get_field_id( 'terms' ); ?>" name="<?php echo $this->get_field_name( 'terms' ); ?>"  value="<?php echo $val['terms'];?>"/><br />Separate multiple Tags/Categories with ",".
        </p>