<h4 style="border-bottom: 1px solid #ccc" >Display Settings</h4>
        <p><label>Display As: </label>
    	<select id="<?php echo $widget->get_field_id( 'display' ); ?>" name="<?php echo $widget->get_field_name( 'display' ); ?>">
        	<option value="list" <?php selected( $val['display'], 'list'); ?>>List</option>
            <option value="promo" <?php selected( $val['display'], 'promo'); ?>>Image Promo</option>
            <option value="column_promo" <?php selected( $val['display'], 'column_promo'); ?>>Column Promo</option>
        </select></p>
       