 <p><label>Count: </label>
    	<input type="text" id="<?php echo $widget->get_field_id( 'count' ); ?>" name="<?php echo $widget->get_field_name( 'count' ); ?>" value="<?php echo $val['count'];?>"/><br /></p>
        <p><label>Skip First: </label>
    	<input type="text" id="<?php echo $widget->get_field_id( 'skip' ); ?>" name="<?php echo $widget->get_field_name( 'skip' ); ?>" value="<?php echo $val['skip'];?>"/><br /></p>