
            <p class="input-wrap">
            	<input class="hidden-input" type="checkbox" name="<?php echo $this->get_field_name( 'display_title' ); ?>" checked="checked" value="0" /> 
                <input type="checkbox" name="<?php echo $this->get_field_name( 'display_title' ); ?>" value="1" <?php checked( $in['display_title'], 1 ); ?> /> Display Title <br />
                
                <input class="hidden-input" type="checkbox" name="<?php echo $this->get_field_name( 'display_excerpt' ); ?>" checked="checked" value="0" /> 
                <input type="checkbox" name="<?php echo $this->get_field_name( 'display_excerpt' ); ?>" value="1" <?php checked( $in['display_excerpt'], 1 ); ?> /> Display Summary Text<br />
                
                <input class="hidden-input" type="checkbox" name="<?php echo $this->get_field_name( 'display_content' ); ?>" checked="checked" value="0" /> 
                <input type="checkbox" name="<?php echo $this->get_field_name( 'display_content' ); ?>" value="1" <?php checked( $in['display_content'], 1 ); ?>/> Display Full Text<br />
                
                <input class="hidden-input" type="checkbox" name="<?php echo $this->get_field_name( 'display_image' ); ?>" checked="checked" value="0" /> 
                <input type="checkbox" name="<?php echo $this->get_field_name( 'display_image' ); ?>" value="1"  <?php checked( $in['display_image'], 1 ); ?>/> Display Image<br />
                
                <input class="hidden-input" type="checkbox" name="<?php echo $this->get_field_name( 'display_link' ); ?>" checked="checked" value="0" /> 
                <input type="checkbox" name="<?php echo $this->get_field_name( 'display_link' ); ?>" value="1" <?php checked( $in['display_link'], 1 ); ?>/> Link to Content<br />
                <input class="hidden-input" type="checkbox" name="<?php echo $this->get_field_name( 'display_meta' ); ?>" checked="checked" value="0" /> 
                <input type="checkbox" name="<?php echo $this->get_field_name( 'display_meta' ); ?>" value="1" <?php checked( $in['display_meta'], 1 ); ?>/> Display Meta (Date, Author, etc..)<br />
                <span class="input-helper">*** Options may not be applicable to selected display style.</span>
            </p>